server:
  port: 9000
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


app:
  threadPool:
    core-pool-size: 4
    maximum-pool-size: 8
    keep-alive-time: 60
    work-queue-size: 200
