server:
  port: 14000
spring:
  profiles:
    include: sharding
  main:
    allow-bean-definition-overriding: true
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  rabbitmq:
    host: 192.168.200.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true











