server:
  port: 7000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

app:
  minio:
    accessKey: admin
    secretKey: admin123456
    endpoint: http://192.168.200.128:9000
    bucketName: gmall