server:
  port: 7000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.153.200:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
